# Generated by Django 5.2.8 on 2025-12-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='内容')),
                ('excerpt', models.CharField(blank=True, max_length=300, verbose_name='抜粋')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_published', models.BooleanField(default=True, verbose_name='公開')),
            ],
            options={
                'verbose_name': 'ブログ記事',
                'verbose_name_plural': 'ブログ記事',
                'ordering': ['-created_at'],
            },
        ),
    ]
