# Generated by Django 5.2.8 on 2025-12-09 15:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-post_date'], 'verbose_name': 'ブログ記事', 'verbose_name_plural': 'ブログ記事'},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('tech', '技術'), ('daily', '日常'), ('work', '就活'), ('hobby', '趣味'), ('travel', '旅行'), ('other', 'その他')], default='other', max_length=20, verbose_name='カテゴリ'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name='画像'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日時'),
        ),
    ]
