# Generated by Django 4.2 on 2026-01-27 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0003_create_initial_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('tech', '技術'), ('daily', '日常'), ('work', '就活'), ('hobby', '趣味'), ('travel', '旅行'), ('values', '価値観'), ('event', 'イベント'), ('other', 'その他')], default='other', max_length=20, verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.CharField(blank=True, default='', help_text='staticfiles/img/ 内のファイル名を指定（例: blog-header.jpg）', max_length=255, verbose_name='画像パス'),
        ),
    ]
