# Generated by Django 4.2 on 2026-01-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0004_alter_blogpost_category_alter_blogpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='likes_count',
            field=models.IntegerField(default=0, verbose_name='良いね数'),
        ),
    ]
