# Generated by Django 4.2 on 2026-02-02 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0011_migrate_chapter_titles_to_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='chapter_number',
            field=models.IntegerField(blank=True, help_text='非推奨：代わりにセクション選択を使用してください', null=True, verbose_name='章番号（旧）'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='chapter_order',
            field=models.IntegerField(blank=True, help_text='同じセクション内での表示順序（数値が小さいほど上）', null=True, verbose_name='セクション内順序'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='chapter_title',
            field=models.CharField(blank=True, help_text='非推奨：代わりにセクション選択を使用してください', max_length=100, verbose_name='セクション名（旧）'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='section',
            field=models.ForeignKey(blank=True, help_text='章構成ビューでのグループ（推奨）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='intro.section', verbose_name='セクション'),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, help_text='このセクションの説明（任意）', verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='section',
            name='icon',
            field=models.CharField(blank=True, help_text='絵文字など（例: 📖, 💻, 🚀）', max_length=10, verbose_name='アイコン'),
        ),
        migrations.AlterField(
            model_name='section',
            name='is_active',
            field=models.BooleanField(default=True, help_text='無効にすると章構成ビューに表示されません', verbose_name='有効'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(help_text='例: 資格、技術、プロジェクト、第1章など', max_length=100, unique=True, verbose_name='セクション名'),
        ),
        migrations.AlterField(
            model_name='section',
            name='order',
            field=models.IntegerField(default=0, help_text='数値が小さいほど上に表示されます', verbose_name='表示順'),
        ),
    ]
