# Generated by Django 4.2 on 2026-02-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0012_alter_blogpost_chapter_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='お名前')),
                ('design', models.IntegerField(help_text='1-5', verbose_name='サイトの見やすさ・デザイン')),
                ('portfolio', models.IntegerField(help_text='1-5', verbose_name='作品紹介の評価')),
                ('dx_ai', models.IntegerField(help_text='1-5', verbose_name='DX×AI作品の評価')),
                ('navigation', models.IntegerField(help_text='1-5', verbose_name='ナビゲーションの使いやすさ')),
                ('information', models.IntegerField(help_text='1-5', verbose_name='情報の分かりやすさ')),
                ('overall', models.IntegerField(help_text='1-5', verbose_name='全体的な満足度')),
                ('message', models.TextField(blank=True, verbose_name='ご意見・ご感想')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='送信日時')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IPアドレス')),
                ('user_agent', models.TextField(blank=True, verbose_name='ユーザーエージェント')),
            ],
            options={
                'verbose_name': 'お問い合わせ',
                'verbose_name_plural': 'お問い合わせ一覧',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
