# Generated by Django 4.2 on 2026-02-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0013_contactformsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='作品タイトル')),
                ('description', models.TextField(verbose_name='説明')),
                ('thumbnail', models.ImageField(upload_to='portfolio_images/', verbose_name='サムネイル画像')),
                ('demo_url', models.URLField(blank=True, help_text='作品のデモページURL', verbose_name='デモURL')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHubリポジトリURL')),
                ('technologies', models.CharField(help_text='カンマ区切りで入力（例: Python, Django, PostgreSQL）', max_length=500, verbose_name='使用技術')),
                ('display_order', models.IntegerField(default=0, help_text='数値が小さいほど上に表示', verbose_name='表示順')),
                ('is_published', models.BooleanField(default=True, verbose_name='公開')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '作品',
                'verbose_name_plural': '作品',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
