# Generated by Django 4.2 on 2026-02-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0014_portfolioitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='thumbnail',
            field=models.CharField(blank=True, default='', help_text='staticfiles/img/ 内のファイル名を指定（例: 100年後の東京.jpg）', max_length=255, verbose_name='サムネイル画像パス'),
        ),
    ]
